In [56]:
#Dependencies
import numpy
import pandas as pd
import os
import csv

In [149]:
#Load in the file from local machine
demographics_file = "Demographics2018.csv"
demographics_Age = "DemographicsAge2018.csv"

#Read the disfile and display the CSV with Pandas :D
demographics_file_pd = pd.read_csv(demographics_file)
demographics_Age_pd = pd.read_csv(demographics_Age)
demographics_Age_pd.head()

,Voter File ID,Address,City,State,Zip,Sex,LastName,FirstName,MiddleName,Suffix,CD,SD,HD,Preferred Phone
0,858681,7584 E Mercer Pl,Denver,CO,80237,F,Basky,Charla,Dee,NaN,1,31,9,3.039039e+09
1,858735,7645 E Quincy Ave Apt 108,Denver,CO,80237,F,Barr,Rose,Marie,NaN,1,31,9,7.202010e+09
2,858737,7755 E Quincy Ave Apt T12,Denver,CO,80237,F,Kyle,Lina,Marie,NaN,1,31,9,3.038754e+09
3,858750,4031 S Quebec St,Denver,CO,80237,F,McCollister,Deborah,Hopper,NaN,1,31,9,3.037587e+09
4,858838,4053 S Quince St,Denver,CO,80237,F,Marshall,Beverly,A,NaN,1,31,9,3.034888e+09

In [151]:
demographics_Age_pd.head()

,Voter File VAN ID,LastName,FirstName,MiddleName,Suffix,Age,Party,mAddress,mCity,mState,mZip5,Sex,Preferred Phone
0,858740,Trujillo,Mario,NaN,NaN,38,U,7755 E Quincy Ave Apt A1-103,Denver,CO,80237,M,NaN
1,858767,Farahmandifard,Jamsheed,NaN,NaN,56,U,7665 E Quincy Ave Apt 208,Denver,CO,80237,M,3.037714e+09
2,858769,Ortiz,Joseph,A,NaN,55,G,4042 S Reading Way,Denver,CO,80237,M,7.204270e+09
3,858798,Muwanga,Brian,Solomon,NaN,52,D,4087 S Quebec St,Denver,CO,80237,M,3.032939e+09
4,858815,Herr,William,M,NaN,60,U,7674 E Mercer Pl,Denver,CO,80237,M,3.037702e+09

In [152]:

#List out the columns in the file 
demographics_Age_pd.columns

Index(['Voter File VAN ID', 'LastName', 'FirstName', 'MiddleName', 'Suffix',
       'Age', 'Party', 'mAddress', 'mCity', 'mState', 'mZip5', 'Sex',
       'Preferred Phone '],
      dtype='object')

In [160]:
#Find the Length... make sure we have gender for everyone
demographics_Age_pd.count()
demographics_Age_pd["Sex", "Age"].head()

KeyError: ('Sex', 'Age')

In [145]:

#List the number of men and women who voted in the 2018 general election
Votes_by_gender = demographics_Age_pd["Sex"].value_counts()

Votes_by_gender

Gender_df = 
#Total_Votes =len(demographics_file_pd)

#Male_Voters = demographics_file_pd.loc[demographics_file_pd["Sex"] == "M"].count()
#total_voting = len(demographics_file_pd)
#percentage_fem = Female_Voters / total_voting
#percentage_male = Male_Voters / total_voting

#print(percentage_fem)
#Perc_DF = pd.DataFrame({"Female turnout": [percentage_fem],
           #"Male turnout": [percentage_male]})
    
#female_percent = Female_Voters / 

#Gender_Diff_df.head()
#Create a column for percentages of M/F Voters
#totalSampleVoters = len(demographics_file_pd)

#Votes_by_gender_df = pd.DataFrame ({"Female Voters": Votes_by_gender})

#Votes_by_gender_df.head

0         True
1         True
2         True
3         True
4         True
5        False
6         True
7         True
8         True
9         True
10        True
11        True
12       False
13        True
14        True
15       False
16        True
17       False
18       False
19       False
20       False
21        True
22       False
23        True
24       False
25        True
26       False
27       False
28        True
29       False
         ...
49428     True
49429     True
49430    False
49431     True
49432     True
49433     True
49434    False
49435     True
49436     True
49437    False
49438     True
49439     True
49440     True
49441    False
49442    False
49443     True
49444    False
49445    False
49446     True
49447     True
49448    False
49449     True
49450    False
49451     True
49452    False
49453     True
49454     True
49455    False
49456     True
49457     True
Name: Sex, Length: 49458, dtype: bool

F    25996
M    23462
Name: Sex, dtype: int64

In [86]:
#Show a histogram of each age group and the percentage of their voter turnout

In [ ]:
#Show a histogram of each PRECINCT in the sample and the percentage of m vs women voters

In [ ]:
#Compare this to national Data??? 
#Look at a map or some shit????